#! /bin/bash

TEMP_FILE=temp_file
IP_FILE=mint

ip addr | grep -o "inet 172..*" | cut -f 2 -d ' ' | cut -f 1 -d / > "$TEMP_FILE"
scp -i /home/charlie/.ssh/Home-2019-10-27 /home/charlie/Source/"$TEMP_FILE" pi2:/home/pi/Git/hyperv-stuff/"$IP_FILE"
rm "$TEMP_FILE"

echo "Sent "$IP_FILE" to raspberry pi"
